all: server guida visitatore

server:	server.c
	gcc -Wall server.c -o server

guida:	guida.c
	gcc -Wall guida.c -o guida

visitatore:	visitatore.c
	gcc -Wall visitatore.c -o visitatore
clean:
	rm -f server guida visitatore

